name: Deploy Portfolio
on:
  push:
    branches: [ main ] # Se activa al subir cambios a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            # 1. Asegurar que el directorio existe y tenemos permisos
            # Intentamos entrar, si no existe, clonamos el repo
            [ -d "/var/www/portfolio" ] || git clone https://github.com/josealpma/portfolio-minified.git /var/www/portfolio
            cd /var/www/portfolio || exit

            # 2. Actualizar el código
            # Forzamos el pull para evitar conflictos de archivos locales
            git fetch --all
            git reset --hard origin/main
            
            # 3. Instalación de dependencias y Build
            # Usamos npm install para asegurar que todas las librerías de Astro estén listas
            npm install
            npm run build

            # 4. Gestión con PM2
            # Detenemos el proceso anterior si existe y lanzamos el nuevo servidor
            # La opción -s es para Single Page Apps y -l especifica el puerto 3000
            pm2 delete portfolio || true
            pm2 start "npx serve -s dist -l 3000" --name "portfolio"
            
            # Guardar la configuración para que sobreviva a reinicios del VPS
            pm2 save
