name: Deploy Portfolio
on:
  push:
    branches: [ main ] # Se activa al subir cambios a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/${{ secrets.USERNAME }}/portfolio || git clone https://github.com/josealpma/portfolio-minified.git /home/${{ secrets.USERNAME }}/portfolio
            cd /home/${{ secrets.USERNAME }}/portfolio
            git pull origin main
            npm install
            npm run build
            # Servir con PM2 (ajusta el puerto si es necesario)
            pm2 delete portfolio || true
            pm2 start npx --name "portfolio" -- serve dist/ --port 3000
